openapi: 3.0.0
info:
  title: Service mesh test
  description: >
    `Design First`, `Validated`
  version: 1.0.0
  contact:
    name: My Test Team
    url: https://wiki.mail.ru/display/my_test
    email: my_test@mail.ru
servers:
  - url: /api
    description: Starting path of my test servers url
security:
  - basicAuth: []
tags:
  - name: Transmitter
    description: Аутентификация и авторизация
paths:
  /callping:
    get:
      tags:
        - Transmitter
      summary: Set new value, if count > 10 then return '400'
      operationId: callping
      responses:
        '200':
          description: return request parameter value
          content:
            application/json:
              schema:
                type: string
  /callcount:
    get:
      tags:
        - Transmitter
      summary: Return current counter
      operationId: callcount
      responses:
        '200':
          description: return current counter
          content:
            application/json:
              schema:
                type: string
