openapi: 3.0.0
info:
  title: Аутентификация
  description: >
    `Design First`, `Validated`
  version: 1.0.0
  contact:
    name: My Test Team
    url: https://wiki.mail.ru/display/my_test
    email: my_test@mail.ru
servers:
  - url: /api
    description: Starting path of my test servers url
security:
  - basicAuth: []
tags:
  - name: Authentication
    description: Аутентификация и авторизация
paths:
  /login:
    post:
      summary: Логин пользователя
      operationId: login
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInfo'
        required: true
      responses:
        '200':
          description: Ответ с токенами и информацией о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
        '401':
          description: Некорректный логин или пароль
        '403':
          description: >-
            Логин и пароль корректны, но пользователь не обладает допустимой ролью
  /tokens/refresh:
    get:
      summary: Обновление пары токенов
      operationId: refreshTokens
      tags:
        - Authentication
      responses:
        '200':
          description: Токены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '401':
          description: Некорректный логин или пароль
        '403':
          description: >-
            Логин и пароль корректны, но пользователь не обладает допустимой ролью
  /logout:
    get:
      summary: Логаут пользователя
      operationId: logout
      tags:
        - Authentication
      responses:
        '401':
          description: Некорректный логин или пароль (после редиректа на /api/login)
  /create:
    put:
      summary: Создание пользователя
      operationId: create
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInfo'
      responses:
        '200':
          description: Ответ с токенами и информацией о пользователе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authentication'
        '403':
          description: >-
            Такой пользователь уже существует
components:
  schemas:
    Authentication:
      allOf:
        - $ref: '#/components/schemas/TokenPair'
        - $ref: '#/components/schemas/User'
    User:
      properties:
        username:
          description: Логин пользователя
          type: string
          example: '12345'
        firstName:
          description: Имя пользователя
          type: string
          example: Иван
        lastName:
          description: Фамилия пользователя
          type: string
          example: Петров
        roles:
          type: array
          description: >-
            Роли пользователя (допустимые для использования
            обладающие максимальным уровнем)
          items:
            type: string
            example: ["Manager"]
    TokenPair:
      properties:
        accessToken:
          $ref: '#/components/schemas/Token'
        refreshToken:
          $ref: '#/components/schemas/Token'
    Token:
      properties:
        value:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4ODgiLCJsb2dpblRpbWUiOjE1NTk3NDA0MTA3NjcsInR5cGUiOiJhY2Nlc3MiLCJleHAiOjE1NTk3NDIyMTAsImlhdCI6MTU1OTc0MDQxMH0.6oRpW8nXpG6kFQZbOTPrJ9hLZ0iGK3PXYc5GfbADHmM
        expirationDateTime:
          type: string
          format: date-time
          pattern: "DD-MM-YYYY HH:mm:ss"
          example: 01.01.2020 16:35:46
    AuthInfo:
      required:
        - password
        - login
      type: object
      properties:
        userName:
          type: string
          example: Vasya
        passwordHash:
          type: string
          description: MD5 hashed password
          format: password
          example: f1294cd41b8a0a0c403911bb212d9edf
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
