server:
  port: 8181
service1:
  authenticationsControllerUri: /api
springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger-ui.html
authentication:
  logon:
    topic:
      name: logon
spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
kafka:
  bootstrap:
    servers: localhost:9092
  acks: all
  retries: 0
  batch:
    size: 16384
  linger:
    ms: 1
  buffer:
    memory: 4096000
  key:
    serializer: org.apache.kafka.common.serialization.StringSerializer
  value:
    serializer: org.apache.kafka.common.serialization.StringSerializer