server:
  port: 8080
  host: 0.0.0.0
metrics:
  rest-request:
    enabled: false
tracing:
  service: "svc_ping"
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/health"
      enabled: false